In [295]:
import pandas as pd

In [296]:
df = pd.read_csv("movies_2.csv", index_col = "MovieID")
df.head(10)

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
MovieID,,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
6,Uncle Buck,PG,15000000.0,79258538.0,1989-08-16,Family,100.0,7.0,77659.0,Bachelor and all-round slob Buck babysits his ...
7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
9,Parenthood,PG-13,20000000.0,126297830.0,1989-07-31,Comedy,124.0,7.0,41866.0,The Buckmans are a midwestern family all deali...
10,Lethal Weapon 2,R,25000000.0,227853986.0,1989-07-07,Comedy,114.0,7.2,151737.0,Riggs and Murtaugh are on the trail of South A...

In [297]:
df.tail(10)

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
MovieID,,,,,,,,,,
607,Spider-Man: Far from Home,PG-13,160000000.0,1.131000e+09,2019-06-26,Action,129.0,NaN,NaN,NaN
608,Dumbo,PG,170000000.0,3.530000e+08,2019-03-11,Adventure,112.0,NaN,NaN,NaN
609,Captain Marvel,PG-13,175000000.0,1.128000e+09,2019-02-27,Action,124.0,NaN,NaN,NaN
610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,NaN,NaN,NaN
611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,NaN,NaN,NaN
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [298]:
# the number of rows and columns present in the data set 
df.shape

(616, 10)

In [331]:
# columns present in the data set, along with the data type
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 616 entries, 1 to 0
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         615 non-null    object
 1   MPAA Rating   615 non-null    object
 2   Budget        615 non-null    float64
 3   Gross         615 non-null    float64
 4   Release Date  615 non-null    object
 5   Genre         615 non-null    object
 6   Runtime       615 non-null    float64
 7   Rating        508 non-null    float64
 8   Rating Count  508 non-null    float64
 9   Summary       496 non-null    object
dtypes: float64(5), object(5)
memory usage: 52.9+ KB

In [300]:
df.dtypes

Title            object
MPAA Rating      object
Budget          float64
Gross           float64
Release Date     object
Genre            object
Runtime         float64
Rating          float64
Rating Count    float64
Summary          object
dtype: object

In [ ]:
# df["Gross"] =  df['Gross'].astype(int)

In [301]:
df.isna().sum()

Title             1
MPAA Rating       1
Budget            1
Gross             1
Release Date      1
Genre             1
Runtime           1
Rating          108
Rating Count    108
Summary         120
dtype: int64

In [302]:
df_one = df.drop(["Summary"], axis = 1)
df_one

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [313]:
df_two = df_one.rename(columns={"MovieID": "movie_id", "Title": "title","MPAA Rating": "mpaa_rating","Budget": "budget", "Gross": "gross", "Release Date": "release_date","Genre": "genre","Runtime": "runtime", "Rating":"rating", "Rating Count":"rating_count"})
df_two

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [314]:
df_three = df_two[:-1]
df_three

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,NaN,NaN
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN

In [315]:
df_three.isna().sum()

title             0
mpaa_rating       0
budget            0
gross             0
release_date      0
genre             0
runtime           0
rating          107
rating_count    107
dtype: int64

In [316]:
# we have missing data in column "rating" and "rating count"
# find the mean and median from "rating" and "rating count"

df_mean = df_three.mean()
df_mean

budget          9.491710e+07
gross           4.453221e+08
runtime         1.186423e+02
rating          6.917323e+00
rating_count    3.392521e+05
dtype: float64

In [317]:
# use fillna() method to replace the missing values of Rating with their median

df_three["rating"] = df_three["rating"].fillna(value = df_three["rating"].mean())


df_three

<ipython-input-317-641c851572cb>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_three["rating"] = df_three["rating"].fillna(value = df_three["rating"].mean())

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.900000,73638.0
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.400000,91075.0
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.200000,91415.0
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.200000,91415.0
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.500000,101702.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.917323,NaN
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.917323,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.917323,NaN
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.917323,NaN
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.917323,NaN

In [318]:
df_three["rating_count"] = df_three["rating_count"].fillna(value = df_three["rating_count"].mean())
df_three

<ipython-input-318-ad45f1295635>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_three["rating_count"] = df_three["rating_count"].fillna(value = df_three["rating_count"].mean())

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.900000,73638.000000
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.400000,91075.000000
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.200000,91415.000000
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.200000,91415.000000
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.500000,101702.000000
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.917323,339252.120079
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.917323,339252.120079
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.917323,339252.120079
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.917323,339252.120079
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.917323,339252.120079

In [319]:
df_three.shape

(615, 9)

In [321]:
df_three.isna().sum()

title           0
mpaa_rating     0
budget          0
gross           0
release_date    0
genre           0
runtime         0
rating          0
rating_count    0
dtype: int64

In [322]:
df_four = df_three.drop_duplicates()
df_four

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.900000,73638.000000
2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.400000,91075.000000
3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.200000,91415.000000
4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.200000,91415.000000
5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.500000,101702.000000
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.917323,339252.120079
612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.917323,339252.120079
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.917323,339252.120079
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.917323,339252.120079
615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.917323,339252.120079

In [323]:
duplicateRows = df_three[df_three.duplicated()]
duplicateRows

Empty DataFrame
Columns: [title, mpaa_rating, budget, gross, release_date, genre, runtime, rating, rating_count]
Index: []

In [332]:
# This is where we used a parameter keep = false to show all duplicates

duplicateRows_title = df_three[df_three.duplicated(['title'], keep = False)]
duplicateRows_title

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
22,Teenage Mutant Ninja Turtles,PG,13500000.0,2.020000e+08,1990-03-30,Action,93.0,6.800000,7.980600e+04
47,Beauty and the Beast,PG,25000000.0,3.773506e+08,1991-11-13,Animation,84.0,8.000000,3.974670e+05
66,Aladdin,G,28000000.0,5.040502e+08,1992-11-25,Animation,90.0,8.000000,3.363840e+05
99,Jurassic Park III,PG-13,93000000.0,3.688000e+08,2001-07-16,Thriller,92.0,8.900000,1.690474e+06
108,The Lion King,G,45000000.0,7.882418e+08,1994-06-23,Animation,89.0,8.500000,8.691270e+05
196,Godzilla,PG-13,130000000.0,3.790143e+08,1998-05-20,Thriller,139.0,5.400000,1.746000e+05
250,Jurassic Park III,PG-13,93000000.0,3.687808e+08,2001-07-18,Adventure,92.0,5.900000,2.801100e+05
502,Teenage Mutant Ninja Turtles,PG-13,125000000.0,4.772000e+08,2014-08-07,Action,101.0,5.800000,1.940730e+05
505,Godzilla,PG-13,160000000.0,5.290761e+08,2014-05-14,Thriller,123.0,6.400000,3.594380e+05
566,Beauty and the Beast,PG,160000000.0,1.262886e+09,2017-03-16,Drama,129.0,6.917323,3.392521e+05
610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.917323,3.392521e+05
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.917323,3.392521e+05

In [330]:
without_duplicate = duplicateRows_title.drop_duplicates()
without_duplicate

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
250,Jurassic Park III,PG-13,93000000.0,3.687808e+08,2001-07-18,Adventure,92.0,5.900000,280110.000000
502,Teenage Mutant Ninja Turtles,PG-13,125000000.0,4.772000e+08,2014-08-07,Action,101.0,5.800000,194073.000000
505,Godzilla,PG-13,160000000.0,5.290761e+08,2014-05-14,Thriller,123.0,6.400000,359438.000000
566,Beauty and the Beast,PG,160000000.0,1.262886e+09,2017-03-16,Drama,129.0,6.917323,339252.120079
610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.917323,339252.120079
614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.917323,339252.120079

In [ ]:
# Convert Budget into integer type (use astype() method)
df_four = df_three.astype({'budget':'int'})

df_four

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000,3.859000e+08,2019-05-13,Adventure,132.0,NaN,NaN
612,Toy Story 4,G,200000000,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN

In [ ]:
df_four.dtypes

title            object
mpaa_rating      object
budget            int32
gross           float64
release_date     object
genre            object
runtime         float64
rating          float64
rating_count    float64
dtype: object

In [ ]:
# convert "gross" to integer

df_five = df_four.astype({'gross':'int'})
df_five

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000,296000000,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000,71079915,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000,161001698,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000,84431625,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000,385900000,2019-05-13,Adventure,132.0,NaN,NaN
612,Toy Story 4,G,200000000,1062000000,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000,759400000,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000,1632000000,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN

In [ ]:
df_five.dtypes

title            object
mpaa_rating      object
budget            int32
gross             int32
release_date     object
genre            object
runtime         float64
rating          float64
rating_count    float64
dtype: object

In [ ]:
# Convert Release Date into date type (use to_datetime method)

# df_six = df_five.to_datetime({"release_date" : ""})

df_five["release_date"] = pd.to_datetime(df_five["release_date"], format = "%Y/%m/%d")

In [ ]:
df_five.dtypes

title                   object
mpaa_rating             object
budget                   int32
gross                    int32
release_date    datetime64[ns]
genre                   object
runtime                float64
rating                 float64
rating_count           float64
dtype: object

In [360]:
cleaned_df = df_five
cleaned_df

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
1,Look Who's Talking,PG-13,7500000,296000000,1989-10-12,Romance,93.0,5.9,73638.0
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000,71079915,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000,161001698,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000,84431625,1989-04-21,Drama,107.0,7.5,101702.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000,385900000,2019-05-13,Adventure,132.0,NaN,NaN
612,Toy Story 4,G,200000000,1062000000,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000,759400000,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000,1632000000,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN

In [ ]:
cleaned_df.dtypes

title                   object
mpaa_rating             object
budget                   int32
gross                    int32
release_date    datetime64[ns]
genre                   object
runtime                float64
rating                 float64
rating_count           float64
dtype: object

In [ ]:
# show the movies with more than 7 in Rating & greater than 50 million Gross
cleaned_df[(cleaned_df["rating"] > 7) & (cleaned_df["gross"] > 50000000)]

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000,71079915,1989-07-28,Crime,100.0,7.2,91415.0
4,Born on the Fourth of July,R,14000000,161001698,1989-12-20,War,145.0,7.2,91415.0
5,Field of Dreams,PG,15000000,84431625,1989-04-21,Drama,107.0,7.5,101702.0
7,When Harry Met Sally...,R,16000000,92800000,1989-07-21,Romance,96.0,7.6,180871.0
...,...,...,...,...,...,...,...,...,...
506,Big Hero 6,PG,165000000,652105443,2014-10-24,Animation,102.0,7.8,380953.0
507,Interstellar,PG-13,165000000,675120017,2014-11-05,Science Fiction,169.0,8.6,1343549.0
508,Captain America: The Winter Soldier,PG-13,170000000,714766572,2014-03-20,Action,136.0,7.7,685903.0
509,Dawn of the Planet of the Apes,PG-13,170000000,710644566,2014-06-26,Science Fiction,130.0,7.6,395425.0
510,Guardians of the Galaxy,PG-13,170000000,773328629,2014-07-30,Action,121.0,8.0,978222.0

In [ ]:
# show the movies with more than 7 in Rating & greater than 50 million Gross & with Parental guidance as MPAA Rating

selected_movie = cleaned_df[(cleaned_df["rating"] > 7) & (cleaned_df["gross"] > 50000000) & (cleaned_df["mpaa_rating"] == "PG")]
selected_movie

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
3,Turner & Hooch,PG,13000000,71079915,1989-07-28,Crime,100.0,7.2,91415.0
5,Field of Dreams,PG,15000000,84431625,1989-04-21,Drama,107.0,7.5,101702.0
8,Dead Poets Society,PG,16400000,235860116,1989-06-02,Drama,129.0,8.1,382002.0
14,Batman,PG,35000000,411348924,1989-06-23,Action,126.0,7.5,319517.0
16,The Little Mermaid,PG,40000000,222300000,1989-11-17,Animation,83.0,7.6,219221.0
17,Back to the Future Part II,PG,40000000,332000000,1989-11-20,Science Fiction,108.0,7.8,438940.0
20,Steel Magnolias,PG,15000000,95904091,1989-11-15,Drama,119.0,7.3,43037.0
25,Home Alone,PG,18000000,476684675,1990-11-09,Family,103.0,7.6,414472.0
33,The Hunt for Red October,PG,30000000,199200000,1990-03-02,Thriller,134.0,7.6,167212.0
35,Back to the Future Part III,PG,40000000,244527583,1990-05-25,Family,118.0,7.4,369652.0
46,Teenage Mutant Ninja Turtles II,PG,25000000,78600000,1991-03-22,Action,88.0,8.0,397467.0
47,Beauty and the Beast,PG,25000000,377350553,1991-11-13,Animation,84.0,8.0,397467.0
50,Star Trek VI: The Undiscovered Country,PG,27000000,96900000,1991-12-05,Science Fiction,113.0,7.2,66086.0
73,A League of Their Own,PG,40000000,107458785,1992-07-01,Comedy,128.0,7.2,85932.0
81,Groundhog Day,PG,14600000,70906973,1993-02-11,Comedy,101.0,8.0,549538.0
107,Star Trek: Generations,PG,38000000,120000000,1994-11-17,Science Fiction,118.0,8.5,869127.0
127,Mr. Holland's Opus,PG,31000000,106269971,1995-12-29,Family,137.0,7.3,33906.0
131,Apollo 13,PG,52000000,355237933,1995-06-30,Drama,140.0,7.6,250975.0
175,Contact,PG,90000000,171120329,1997-07-11,Science Fiction,150.0,7.4,239569.0
186,The Truman Show,PG,60000000,264118201,1998-06-04,Comedy,103.0,8.1,859224.0
189,The Prince of Egypt,PG,70000000,218613188,1998-12-15,Animation,99.0,7.1,110340.0
216,Tarzan,PG,150000000,448000000,1999-06-18,Animation,88.0,7.3,187724.0
221,Remember the Titans,PG,30000000,136706683,2000-09-29,Drama,113.0,7.8,186997.0
242,Shrek,PG,60000000,484409218,2001-05-16,Animation,90.0,7.8,574978.0
256,Harry Potter and the Sorcerer's Stone,PG,125000000,975100000,2001-11-04,Fantasy,152.0,7.6,583224.0
262,Ice Age,PG,59000000,383257136,2002-03-10,Animation,81.0,7.5,411963.0
271,Harry Potter and the Chamber of Secrets,PG,100000000,876688482,2002-11-13,Fantasy,161.0,7.4,505027.0
305,The Incredibles,PG,92000000,631442092,2004-11-05,Animation,115.0,8.0,617102.0
310,Harry Potter and the Prisoner of Azkaban,PG,130000000,789804554,2004-05-31,Fantasy,141.0,7.9,501648.0
312,Shrek 2,PG,150000000,919838758,2004-05-19,Animation,93.0,7.2,391295.0
386,Kung Fu Panda,PG,130000000,631744560,2008-06-04,Animation,90.0,7.5,390478.0
411,Monsters vs Aliens,PG,175000000,381509870,2009-03-19,Animation,94.0,7.7,374981.0
412,Up,PG,175000000,735099082,2009-05-13,Animation,96.0,8.2,867393.0
416,Harry Potter and the Half-Blood Prince,PG,250000000,933959197,2009-07-07,Fantasy,153.0,7.6,429384.0
421,Despicable Me,PG,69000000,543513985,2010-07-08,Animation,95.0,7.6,473121.0
426,Megamind,PG,130000000,321887208,2010-10-28,Animation,95.0,7.2,212563.0
429,How to Train Your Dragon,PG,165000000,494878759,2010-03-05,Animation,98.0,8.1,624128.0
436,Tangled,PG,260000000,591794936,2010-11-24,Animation,100.0,7.7,374981.0
448,Puss in Boots: The Three Diablos,PG,130000000,555000000,2011-12-08,Animation,130.0,7.8,727724.0
452,Kung Fu Panda 2,PG,150000000,665692281,2011-05-25,Animation,91.0,7.2,234612.0
462,Hotel Transylvania,PG,85000000,358375603,2012-09-20,Animation,91.0,7.1,208916.0
467,Wreck-It Ralph,PG,165000000,471222889,2012-11-01,Animation,108.0,7.7,354202.0
469,Brave,PG,185000000,538983207,2012-06-21,Animation,93.0,7.1,346490.0
481,Despicable Me 2,PG,76000000,970761885,2013-06-25,Animation,98.0,7.4,350582.0
485,The Croods,PG,135000000,585178928,2013-03-20,Animation,98.0,7.2,180043.0
486,Frozen,PG,150000000,1274219009,2013-11-27,Animation,102.0,7.5,527284.0
499,The Lego Movie,PG,60000000,469160692,2014-02-06,Animation,100.0,7.8,309295.0
504,How to Train Your Dragon 2,PG,145000000,609123048,2014-06-12,Animation,102.0,7.8,285394.0
506,Big Hero 6,PG,165000000,652105443,2014-10-24,Animation,102.0,7.8,380953.0

In [ ]:
selected_movie.shape

(50, 9)

In [ ]:
# count of Animation movies with more than 7 in Rating (use the shape() function)

animation_with_7 = cleaned_df[(cleaned_df["genre"] == "Animation") & (cleaned_df["rating"] > 7) ]
animation_with_7

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
16,The Little Mermaid,PG,40000000,222300000,1989-11-17,Animation,83.0,7.6,219221.0
47,Beauty and the Beast,PG,25000000,377350553,1991-11-13,Animation,84.0,8.0,397467.0
66,Aladdin,G,28000000,504050219,1992-11-25,Animation,90.0,8.0,336384.0
108,The Lion King,G,45000000,788241776,1994-06-23,Animation,89.0,8.5,869127.0
124,Toy Story,G,30000000,373554033,1995-10-30,Animation,81.0,8.3,820625.0
172,Hercules,G,85000000,252712101,1997-06-26,Animation,93.0,7.3,188044.0
189,The Prince of Egypt,PG,70000000,218613188,1998-12-15,Animation,99.0,7.1,110340.0
192,Mulan,G,90000000,304320254,1998-06-18,Animation,88.0,7.6,229669.0
195,A Bug's Life,G,120000000,363258859,1998-11-25,Animation,95.0,7.2,251436.0
212,Toy Story 2,G,90000000,497366869,1999-10-30,Animation,92.0,7.9,489299.0
216,Tarzan,PG,150000000,448000000,1999-06-18,Animation,88.0,7.3,187724.0
242,Shrek,PG,60000000,484409218,2001-05-16,Animation,90.0,7.8,574978.0
262,Ice Age,PG,59000000,383257136,2002-03-10,Animation,81.0,7.5,411963.0
287,Finding Nemo,G,94000000,940335536,2003-05-30,Animation,100.0,8.1,887773.0
305,The Incredibles,PG,92000000,631442092,2004-11-05,Animation,115.0,8.0,617102.0
312,Shrek 2,PG,150000000,919838758,2004-05-19,Animation,93.0,7.2,391295.0
350,Cars,G,120000000,461983149,2006-06-08,Animation,117.0,7.1,338715.0
370,Ratatouille,G,150000000,623722818,2007-06-22,Animation,111.0,8.0,594171.0
386,Kung Fu Panda,PG,130000000,631744560,2008-06-04,Animation,90.0,7.5,390478.0
392,WALL-E,G,180000000,533300000,2008-06-23,Animation,97.0,7.6,429384.0
411,Monsters vs Aliens,PG,175000000,381509870,2009-03-19,Animation,94.0,7.7,374981.0
412,Up,PG,175000000,735099082,2009-05-13,Animation,96.0,8.2,867393.0
421,Despicable Me,PG,69000000,543513985,2010-07-08,Animation,95.0,7.6,473121.0
426,Megamind,PG,130000000,321887208,2010-10-28,Animation,95.0,7.2,212563.0
429,How to Train Your Dragon,PG,165000000,494878759,2010-03-05,Animation,98.0,8.1,624128.0
434,Toy Story 3,G,200000000,1066969703,2010-06-16,Animation,103.0,8.3,705408.0
436,Tangled,PG,260000000,591794936,2010-11-24,Animation,100.0,7.7,374981.0
448,Puss in Boots: The Three Diablos,PG,130000000,555000000,2011-12-08,Animation,130.0,7.8,727724.0
452,Kung Fu Panda 2,PG,150000000,665692281,2011-05-25,Animation,91.0,7.2,234612.0
462,Hotel Transylvania,PG,85000000,358375603,2012-09-20,Animation,91.0,7.1,208916.0
467,Wreck-It Ralph,PG,165000000,471222889,2012-11-01,Animation,108.0,7.7,354202.0
469,Brave,PG,185000000,538983207,2012-06-21,Animation,93.0,7.1,346490.0
481,Despicable Me 2,PG,76000000,970761885,2013-06-25,Animation,98.0,7.4,350582.0
485,The Croods,PG,135000000,585178928,2013-03-20,Animation,98.0,7.2,180043.0
486,Frozen,PG,150000000,1274219009,2013-11-27,Animation,102.0,7.5,527284.0
493,Monsters University,G,200000000,743559607,2013-06-20,Animation,104.0,7.3,299133.0
499,The Lego Movie,PG,60000000,469160692,2014-02-06,Animation,100.0,7.8,309295.0
504,How to Train Your Dragon 2,PG,145000000,609123048,2014-06-12,Animation,102.0,7.8,285394.0
506,Big Hero 6,PG,165000000,652105443,2014-10-24,Animation,102.0,7.8,380953.0

In [ ]:
animation_with_7.shape

(39, 9)

In [ ]:
# show the list of top 5 movies based on Budget

movies_sorted_topfive = cleaned_df.sort_values(by=["budget"], ascending = False )
movies_sorted_topfive.head()

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
595,Avengers: Infinity War,PG-13,400000000,2048000000,2018-04-23,Action,149.0,NaN,NaN
455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000,1045713802,2011-05-14,Action,136.0,6.6,455211.0
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN
575,Star Wars: The Last Jedi,PG-13,317000000,1333000000,2019-12-09,Science Fiction,152.0,NaN,NaN
376,Pirates of the Caribbean: At World's End,PG-13,300000000,961000000,2007-05-19,Adventure,169.0,7.1,565402.0

In [ ]:
# show the top 5 Comedy movies by Rating

comedy_movie = cleaned_df[(cleaned_df["genre"] == "Comedy")  ]
comedy_movie

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
9,Parenthood,PG-13,20000000,126297830,1989-07-31,Comedy,124.0,7.0,41866.0
10,Lethal Weapon 2,R,25000000,227853986,1989-07-07,Comedy,114.0,7.2,151737.0
11,The War of the Roses,R,26000000,160200000,1989-12-08,Comedy,116.0,6.8,45248.0
15,Ghostbusters II,PG,37000000,215394738,1989-06-15,Comedy,108.0,6.6,171196.0
...,...,...,...,...,...,...,...,...,...
517,Pitch Perfect 2,PG-13,29000000,287506194,2015-05-07,Comedy,115.0,NaN,NaN
538,Deadpool,R,58000000,783112979,2016-02-09,Comedy,108.0,NaN,NaN
583,Deadpool 2,R,110000000,785000000,2018-05-10,Comedy,119.0,NaN,NaN
598,The Upside,PG-13,37500000,122800000,2019-01-11,Comedy,126.0,NaN,NaN
602,Once Upon a Time in Hollywood,R,96000000,345900000,2019-05-21,Comedy,161.0,NaN,NaN

In [ ]:
comedy_movie.sort_values(by = ["rating"], ascending = False)
print("top 5 comedy movies by rating are: ")
comedy_movie.head()

top 5 comedy movies by rating are:

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
2,Driving Miss Daisy,PG,7500000,145793296,1989-12-13,Comedy,99.0,7.4,91075.0
9,Parenthood,PG-13,20000000,126297830,1989-07-31,Comedy,124.0,7.0,41866.0
10,Lethal Weapon 2,R,25000000,227853986,1989-07-07,Comedy,114.0,7.2,151737.0
11,The War of the Roses,R,26000000,160200000,1989-12-08,Comedy,116.0,6.8,45248.0
15,Ghostbusters II,PG,37000000,215394738,1989-06-15,Comedy,108.0,6.6,171196.0

In [ ]:
# top 5 movie names by Rating

top_five_movies = cleaned_df.sort_values(by = ["rating"], ascending = False)
print("top 5 movie names are: ")
top_five_movies["title"].head()

top 5 movie names are:

MovieID
394                                  The Dark Knight
99                                 Jurassic Park III
288    The Lord of the Rings: The Return of the King
100                                     Pulp Fiction
84                                  Schindler's List
Name: title, dtype: object

In [ ]:
# top 3 high Gross Romance movies released after 1999, not included (typecast it to datetime)

romance_after_millenium = cleaned_df[(cleaned_df["genre"] == "Romance")]
romance_after_millenium.sort_values(by=["gross"], ascending = False )

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
178,Titanic,PG-13,200000000,1845034188,1997-11-18,Romance,194.0,7.8,978389.0
465,The Twilight Saga: Breaking Dawn - Part 2,PG-13,120000000,829000000,2012-11-13,Romance,115.0,5.5,218357.0
443,The Twilight Saga: Breaking Dawn - Part 1,PG-13,110000000,712171856,2011-03-15,Romance,117.0,4.9,211592.0
402,The Twilight Saga: New Moon,PG-13,50000000,709827462,2009-03-15,Romance,130.0,4.7,252223.0
420,The Twilight Saga: Eclipse,PG-13,68000000,698491347,2010-06-23,Romance,124.0,5.0,215110.0
380,Mamma Mia!,PG-13,52000000,609841637,2008-07-03,Romance,108.0,6.4,198801.0
23,Pretty Woman,R,14000000,463000000,1990-03-23,Romance,119.0,7.0,266405.0
578,A Star is Born,R,36000000,435000000,2018-08-31,Romance,135.0,NaN,NaN
379,Twilight,PG-13,37000000,392616625,2008-11-20,Romance,122.0,5.2,400765.0
179,There's Something About Mary,R,23000000,369884651,1998-07-15,Romance,119.0,7.1,278096.0
204,Notting Hill,PG-13,42000000,363889678,1999-05-13,Romance,124.0,7.1,251006.0
104,The Mask,PG-13,23000000,351583407,1994-07-29,Romance,101.0,6.9,320839.0
401,The Proposal,PG-13,40000000,317375031,2009-06-01,Romance,108.0,6.7,277605.0
208,Runaway Bride,PG,70000000,309457509,1999-07-30,Romance,116.0,5.5,88557.0
1,Look Who's Talking,PG-13,7500000,296000000,1989-10-12,Romance,93.0,5.9,73638.0
187,You've Got Mail,PG,65000000,250821495,1998-12-17,Romance,119.0,6.6,180707.0
577,Crazy Rich Asians,PG-13,30000000,238500000,2018-08-07,Romance,121.0,NaN,NaN
83,Sleepless in Seattle,PG,21000000,227799884,1993-06-24,Romance,105.0,6.8,147908.0
218,"Crouching Tiger, Hidden Dragon",PG-13,17000000,213525736,2000-10-01,Romance,120.0,7.8,242878.0
340,The Break-Up,PG-13,52000000,204999686,2006-06-01,Romance,106.0,5.8,119027.0
120,While You Were Sleeping,PG,17000000,182057016,1995-04-21,Romance,103.0,6.7,85626.0
259,Sweet Home Alabama,PG-13,30000000,180622424,2002-09-26,Romance,108.0,6.2,96978.0
240,The Princess Diaries,G,37000000,165335153,2001-08-03,Romance,115.0,6.3,118754.0
7,When Harry Met Sally...,R,16000000,92800000,1989-07-21,Romance,96.0,7.6,180871.0
44,Father of the Bride,PG,20000000,89325780,1991-12-20,Romance,105.0,6.5,64326.0
52,The Prince of Tides,R,30000000,74787599,1991-12-25,Romance,132.0,6.7,14918.0
72,Boomerang,R,40000000,70100000,1992-06-30,Romance,117.0,5.5,24114.0
60,The Crying Game,R,3705538,62548947,1992-09-02,Romance,112.0,7.2,48101.0

In [ ]:
cleaned_df.dtypes

title                   object
mpaa_rating             object
budget                   int32
gross                    int32
release_date    datetime64[ns]
genre                   object
runtime                float64
rating                 float64
rating_count           float64
dtype: object

In [354]:
import datetime as dt 
#(cleaned_df['release_date'].dt.year) > 2000 

cleaned_df[(cleaned_df['release_date'] >= '2000') | (cleaned_df['genre'] == 'Thriller') ]

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
29,Ghost,PG-13,22000000,505000000,1990-07-12,Thriller,127.0,7.0,183054.0
33,The Hunt for Red October,PG,30000000,199200000,1990-03-02,Thriller,134.0,7.6,167212.0
40,Die Hard 2,R,70000000,240031094,1990-07-02,Thriller,124.0,7.2,317843.0
77,Patriot Games,R,45000000,178051587,1992-06-04,Thriller,117.0,6.9,95783.0
78,Basic Instinct,R,49000000,352927224,1992-03-20,Thriller,127.0,6.9,159658.0
...,...,...,...,...,...,...,...,...,...
611,Godzilla: King of the Monsters,PG-13,200000000,385900000,2019-05-13,Adventure,132.0,NaN,NaN
612,Toy Story 4,G,200000000,1062000000,2019-06-11,Animation,100.0,NaN,NaN
613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000,759400000,2019-07-13,Thriller,136.0,NaN,NaN
614,The Lion King,PG,250000000,1632000000,2019-07-09,Drama,118.0,NaN,NaN
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN

In [ ]:
# how many Genres are present in the dataframe? (use the function value_counts() which applies to Series, not Dataframe)
vc = cleaned_df["genre"].value_counts()
vc

Action             110
Comedy              99
Animation           87
Drama               66
Thriller            41
Science Fiction     37
Adventure           30
Family              29
Romance             28
Fantasy             27
Crime               17
Horror              14
Mystery             11
War                  9
Western              6
History              4
Name: genre, dtype: int64

In [356]:
cleaned_df.sort_values(by=["budget"], ascending = False)

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
595,Avengers: Infinity War,PG-13,400000000,2048000000,2018-04-23,Action,149.0,NaN,NaN
455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000,1045713802,2011-05-14,Action,136.0,6.6,455211.0
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN
575,Star Wars: The Last Jedi,PG-13,317000000,1333000000,2019-12-09,Science Fiction,152.0,NaN,NaN
376,Pirates of the Caribbean: At World's End,PG-13,300000000,961000000,2007-05-19,Adventure,169.0,7.1,565402.0
...,...,...,...,...,...,...,...,...,...
297,Fahrenheit 9/11,R,6000000,119114517,2004-06-25,Drama,122.0,7.5,123244.0
258,My Big Fat Greek Wedding,PG,5000000,368744044,2002-02-22,Comedy,95.0,6.5,114907.0
556,Get Out,R,5000000,252434250,2017-02-24,Horror,104.0,NaN,NaN
60,The Crying Game,R,3705538,62548947,1992-09-02,Romance,112.0,7.2,48101.0
199,The Blair Witch Project,R,60000,248000000,1999-07-14,Horror,81.0,6.5,220304.0

In [357]:
# top 5 expensive movies released after 1999, not included (measured by Budget)

movies_topfive = cleaned_df.sort_values(by=["budget"], ascending = False)
movies_topfive = movies_topfive.loc[(movies_topfive["release_date"]>= "2000-01-01")]
movies_topfive
# filter movies released after 1999?

,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count
MovieID,,,,,,,,,
595,Avengers: Infinity War,PG-13,400000000,2048000000,2018-04-23,Action,149.0,NaN,NaN
455,Pirates of the Caribbean: On Stranger Tides,PG-13,380000000,1045713802,2011-05-14,Action,136.0,6.6,455211.0
615,Avengers: Endgame,PG-13,356000000,-2147483648,2019-04-22,Action,181.0,NaN,NaN
575,Star Wars: The Last Jedi,PG-13,317000000,1333000000,2019-12-09,Science Fiction,152.0,NaN,NaN
376,Pirates of the Caribbean: At World's End,PG-13,300000000,961000000,2007-05-19,Adventure,169.0,7.1,565402.0
...,...,...,...,...,...,...,...,...,...
476,The Conjuring,R,13000000,318000141,2013-07-18,Horror,112.0,7.5,410378.0
357,Juno,PG-13,7500000,231411584,2007-12-05,Comedy,96.0,7.4,471466.0
297,Fahrenheit 9/11,R,6000000,119114517,2004-06-25,Drama,122.0,7.5,123244.0
258,My Big Fat Greek Wedding,PG,5000000,368744044,2002-02-22,Comedy,95.0,6.5,114907.0
556,Get Out,R,5000000,252434250,2017-02-24,Horror,104.0,NaN,NaN

In [ ]:
# most & least frequent MPAA Rating in the dataset in terms of occurances (発生頻度からいうと)

frequent_mpaa = cleaned_df["mpaa_rating"].value_counts()
print(frequent_mpaa)
print(f"most frequent MPAA Rating is: ", frequent_mpaa.idxmax())
print(f"least frequent MPAA Rating is: ", frequent_mpaa.idxmin())

PG-13    285
PG       161
R        142
G         27
Name: mpaa_rating, dtype: int64
most frequent MPAA Rating is:  PG-13
least frequent MPAA Rating is:  G

In [ ]:
frequent_mpaa = cleaned_df["mpaa_rating"].value_counts()
print(frequent_mpaa)
print(f"most frequent MPAA Rating is: ", frequent_mpaa.index[0])

PG-13    285
PG       161
R        142
G         27
Name: mpaa_rating, dtype: int64
most frequent MPAA Rating is:  PG-13

In [358]:
# most and least expensive Genre (take an average of all Budget measures grouped by Genre - use groupBy() method)

average_budget = cleaned_df.groupby("genre").mean().reset_index()

average_budget[['gross', 'budget']] = average_budget[['gross', 'budget']].round()

average_budget.sort_values("budget")

# most expensive genre : Fantasy
# least expensive genre: Horror

,genre,budget,gross,runtime,rating,rating_count
9,Horror,37004286.0,272470769.0,116.000000,6.644444,207496.222222
11,Romance,45400198.0,384157040.0,117.285714,6.361538,205984.269231
3,Comedy,49577273.0,244795708.0,105.919192,6.617021,220524.127660
8,History,55500000.0,275317788.0,157.750000,7.625000,448652.000000
5,Drama,55925758.0,298936383.0,126.651515,7.246429,291762.785714
4,Crime,56588235.0,228677948.0,121.941176,6.875000,223550.250000
6,Family,62689655.0,292060909.0,104.172414,6.089286,153538.357143
15,Western,79833333.0,336011107.0,141.500000,7.420000,451161.600000
13,Thriller,86585366.0,396339443.0,121.073171,7.014706,419500.029412
14,War,90755556.0,390375870.0,151.111111,7.412500,411161.000000
10,Mystery,103545455.0,372587934.0,131.454545,6.820000,288529.200000
2,Animation,115879310.0,561741357.0,95.885057,7.190476,325150.920635
12,Science Fiction,126783784.0,525245109.0,126.567568,7.200000,493352.290323
1,Adventure,133833333.0,421979009.0,130.266667,6.665385,399555.076923
0,Action,144168182.0,579608371.0,127.936364,7.023684,477202.539474
7,Fantasy,161211111.0,792605470.0,143.037037,7.436364,602313.954545

In [ ]:
average_budget.sort_values(by = ["budget"])
display(average_budget)
display("The least expensive genre is: Western ")

,budget,gross,runtime,rating,rating_count
genre,,,,,
Action,1.441682e+08,5.796084e+08,127.936364,7.023684,477202.539474
Adventure,1.338333e+08,4.219790e+08,130.266667,6.665385,399555.076923
Animation,1.158793e+08,5.617414e+08,95.885057,7.190476,325150.920635
Comedy,4.957727e+07,2.447957e+08,105.919192,6.617021,220524.127660
Crime,5.658824e+07,2.286779e+08,121.941176,6.875000,223550.250000
Drama,5.592576e+07,2.989364e+08,126.651515,7.246429,291762.785714
Family,6.268966e+07,2.920609e+08,104.172414,6.089286,153538.357143
Fantasy,1.612111e+08,7.926055e+08,143.037037,7.436364,602313.954545
History,5.550000e+07,2.753178e+08,157.750000,7.625000,448652.000000
Horror,3.700429e+07,2.724708e+08,116.000000,6.644444,207496.222222
Mystery,1.035455e+08,3.725879e+08,131.454545,6.820000,288529.200000
Romance,4.540020e+07,3.841570e+08,117.285714,6.361538,205984.269231
Science Fiction,1.267838e+08,5.252451e+08,126.567568,7.200000,493352.290323
Thriller,8.658537e+07,3.963394e+08,121.073171,7.014706,419500.029412
War,9.075556e+07,3.903759e+08,151.111111,7.412500,411161.000000
Western,7.983333e+07,3.360111e+08,141.500000,7.420000,451161.600000

'The least expensive genre is: Western '

In [ ]:
print("This is the most expensive genre: Action")
average_budget.head(1)

This is the most expensive genre: Action

              budget         gross     runtime    rating   rating_count
genre
Action  1.441682e+08  5.796084e+08  127.936364  7.023684  477202.539474

In [ ]:
# which Genre is favored the most by the people?

# action movies